### ISSUE TITLE
Update auth indicator on home page

### ISSUE THREAD

**Issue by morganmspencer** [redwoodjs/playground-auth#44]
Looking to update the indicator on the home page after discussion with @Tobbe and @dthyresson over on #41 

Here's an example of an updated version to get the ball rolling on brainstorming

![image](https://user-images.githubusercontent.com/10109983/115167126-480ef880-a084-11eb-989d-9f034272f153.png)

**Comment by morganmspencer** [comment]
In that example, "Authenticated" or "Not Authenticated" would be hidden for screen readers only

**Comment by Tobbe** [comment]
It's still not clear to me (as an imaginary first time visitor to the site) what "green" means. Installed? Enabled? Selected? 
What about going back to the (pulsating) dot, but add a visible text next to also?
Or place some kind of legend above or below all the buttons?
~Or a hover tooltip?~ Doesn't work very well on mobile...
Or maybe a locked/unlocked symbol would be more clear? Instead of the dot or checkmark I mean.

Just throwing out ideas :)

**Comment by morganmspencer** [comment]
What about something like this? A bit more subtle than the badge but still gets the messaged across.

![image](https://user-images.githubusercontent.com/10109983/115244889-5f84ca80-a0f2-11eb-85d1-3a06fc4b5d71.png)

**Comment by dthyresson** [comment]
@Tobbe what do you think? I like it as well.

**Comment by morganmspencer** [comment]
I also have hidden text appended to the message where the screen reader would read "Signed In to Auth0" or "Signed Out of Auth0"

**Comment by Tobbe** [comment]
Very nice @morganmspencer! Maybe just remove it from the providers that aren't implemented yet. Or replace with some kind of message saying they're not implemented yet
